fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd:
      repo: "https://github.com/camptocamp/puppet-systemd.git"
      ref: "0.4.0"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
  symlinks:
    nfdump: "#{source_dir}"
