fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.1.0"
    systemd:
      repo: "https://github.com/camptocamp/puppet-systemd.git"
      ref: "2.1.0"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
  symlinks:
    nfdump: "#{source_dir}"
