---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.10
  - 2.3.4
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 5.0.0"
